server:
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    name: personal-tailor
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://10.10.198.186:3306/personal_tailor?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: shr0$ett@l@b
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测0需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  redis:
    host: 10.42.40.38
    port: 6379
    password: redistest
    database: 1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # 同一个tomcat下 domain 需确保唯一 ****
  jmx:
    default-domain: personal-tailor
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.rosetta.tailor.entity
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql;pageNum=pagenum;pageSize=pagesize;
  page-size-zero: true
  default-count: false
logging:
  level:
    com.rosetta.face.mapper: debug